# Generated by Django 3.0.4 on 2020-04-15 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todo_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='complete',
        ),
    ]
